var express = require('express');
var MainRouter = express.Router();

var homepage = require('./index');
var users = require('./users');
var items = require('./items');
var checkout = require('./checkout');
var chat = require('./chat');
var merchantsRouter = require('./merchants/sub-routes');
var search = require('./search');
var storefront = require('./storefront');
var purchase = require('./purchase');
var deliverySettings = require('./deliverysettings');
var comparison = require('./comparison');
var dashboard = require('./merchants/dashboard');
var login = require('./login');
var orderDiary = require('./order-diary');
var marketplace = require('./marketplace');
var category = require('./category');
var panel = require('./panel');
var policy = require('./policy');
var activities = require('./activity-log');
var cart = require('./cart');
var subAccount = require('./sub-account');
var approval = require('./approval').approvalRouter;
var quotation = require('./quotation');
var requisition = require('./requisition');
var receivingNote = require('./receiving-note');
var invoice = require('./invoice');
var paymentGateway = require('./payment-gateway');
var userGroups = require('./user-groups');
var accountPermissions = require('./account-permissions');

MainRouter.use('/delivery', deliverySettings);
MainRouter.use('/accounts/', require('./login'));
MainRouter.use('/users', users);
MainRouter.use('/user', users);
MainRouter.use('/items', items);
MainRouter.use('/merchants', merchantsRouter);
MainRouter.use('/storefront/', storefront);
MainRouter.use('/', homepage);
MainRouter.use('/search', search);
MainRouter.use('/checkout/', checkout);
MainRouter.use('/purchase', purchase);
MainRouter.use('/chat', chat);
MainRouter.use('/comparison', comparison);
MainRouter.use('/dashboard', dashboard);
MainRouter.use('/login', login);
MainRouter.use('/orderdiary', orderDiary);
MainRouter.use('/comparison', comparison);
MainRouter.use('/marketplace', marketplace);
MainRouter.use('/category', category);
MainRouter.use('/panel', panel);
MainRouter.use('/policy', policy);
MainRouter.use('/activity-logs', activities);
MainRouter.use('/cart', cart);
MainRouter.use('/subaccount', subAccount);
MainRouter.use('/approval', approval);
MainRouter.use('/quotation', quotation);
MainRouter.use('/requisition', requisition);
MainRouter.use('/receiving-note', receivingNote);
MainRouter.use('/invoice', invoice);
MainRouter.use('/payment-gateway', paymentGateway);
MainRouter.use('/user-groups', userGroups);
MainRouter.use('/account-permissions', accountPermissions);

module.exports = MainRouter;